import { Project } from '@/types/ProjectTypes'

export const projectsData: Project[] = [
  {
    id: 1,
    name: 'Редизайн CRM-панели',
    description: 'Полное обновление интерфейса системы управления клиентами: новая дизайн-система, улучшенная навигация и мобильная адаптация.',
    author: 'Иван Иванов',
    authorId: 1,
    status: 'active',
    priority: 'high',
    progress: 72,
    deadline: '2026-05-20',
    createdAt: '2026-01-10',
    tags: ['Frontend', 'Design'],
    budget: '$18,500',
    teamSize: 5,
  },
  {
    id: 2,
    name: 'API интеграция с 1С',
    description: 'Двусторонняя синхронизация данных с 1С:Предприятие — заказы, склад, финансы. Фоновый обмен без задержек.',
    author: 'Петр Петров',
    authorId: 2,
    status: 'active',
    priority: 'high',
    progress: 45,
    deadline: '2026-06-01',
    createdAt: '2026-02-03',
    tags: ['Backend', 'API'],
    budget: '$32,000',
    teamSize: 4,
  },
  {
    id: 3,
    name: 'Мобильное приложение iOS',
    description: 'Нативное приложение для менеджеров: работа со сделками, задачами и уведомлениями в офлайн-режиме.',
    author: 'Мария Сидорова',
    authorId: 3,
    status: 'active',
    priority: 'high',
    progress: 31,
    deadline: '2026-08-15',
    createdAt: '2026-03-01',
    tags: ['Mobile', 'iOS'],
    budget: '$54,000',
    teamSize: 6,
  },
  {
    id: 4,
    name: 'Аналитика продаж v2',
    description: 'Новые дашборды с детализацией по регионам, менеджерам и товарным категориям. AI-прогноз на следующий квартал.',
    author: 'Алексей Козлов',
    authorId: 4,
    status: 'completed',
    priority: 'medium',
    progress: 100,
    deadline: '2026-03-31',
    createdAt: '2025-12-15',
    tags: ['Analytics', 'Backend'],
    budget: '$21,000',
    teamSize: 3,
  },
  {
    id: 5,
    name: 'Email-рассылки и автоматизация',
    description: 'Конструктор email-кампаний с A/B тестированием, шаблонами и сегментацией базы клиентов.',
    author: 'Елена Новикова',
    authorId: 5,
    status: 'completed',
    priority: 'medium',
    progress: 100,
    deadline: '2026-02-28',
    createdAt: '2025-11-20',
    tags: ['Marketing', 'Backend'],
    budget: '$14,500',
    teamSize: 3,
  },
  {
    id: 6,
    name: 'Система управления складом',
    description: 'Модуль учёта товаров со штрих-кодами, инвентаризацией в реальном времени и интеграцией с поставщиками.',
    author: 'Сергей Волков',
    authorId: 6,
    status: 'paused',
    priority: 'medium',
    progress: 58,
    deadline: '2026-07-10',
    createdAt: '2026-01-25',
    tags: ['Backend', 'Infrastructure'],
    budget: '$27,000',
    teamSize: 4,
  },
  {
    id: 7,
    name: 'Чат-бот поддержки клиентов',
    description: 'AI-чат-бот на основе GPT-4 для первой линии поддержки. Интеграция с Telegram, WhatsApp и веб-виджетом.',
    author: 'Анна Кузнецова',
    authorId: 7,
    status: 'active',
    priority: 'medium',
    progress: 64,
    deadline: '2026-05-30',
    createdAt: '2026-02-14',
    tags: ['AI', 'Backend'],
    budget: '$38,000',
    teamSize: 5,
  },
  {
    id: 8,
    name: 'Двухфакторная аутентификация',
    description: 'Внедрение 2FA через SMS и TOTP-приложения. Обновление политики паролей и шифрования сессий.',
    author: 'Дмитрий Попов',
    authorId: 8,
    status: 'completed',
    priority: 'high',
    progress: 100,
    deadline: '2026-01-31',
    createdAt: '2025-12-01',
    tags: ['Security', 'Backend'],
    budget: '$9,000',
    teamSize: 2,
  },
  {
    id: 9,
    name: 'Кастомизация воронок продаж',
    description: 'Визуальный drag-and-drop конструктор воронок. Пользователи могут создавать сложные сценарии без разработчиков.',
    author: 'Ольга Семёнова',
    authorId: 9,
    status: 'active',
    priority: 'low',
    progress: 18,
    deadline: '2026-09-01',
    createdAt: '2026-03-10',
    tags: ['Frontend', 'CRM'],
    budget: '$16,000',
    teamSize: 3,
  },
  {
    id: 10,
    name: 'Голосовые заметки к сделкам',
    description: 'Возможность прикреплять голосовые записи к контактам и сделкам с автоматической транскрипцией.',
    author: 'Николай Фёдоров',
    authorId: 10,
    status: 'paused',
    priority: 'low',
    progress: 40,
    deadline: '2026-06-20',
    createdAt: '2026-02-20',
    tags: ['Mobile', 'AI'],
    budget: '$11,000',
    teamSize: 2,
  },
  {
    id: 11,
    name: 'Интеграция с AmoCRM',
    description: 'Двусторонний импорт контактов и сделок. Упрощение миграции для новых клиентов платформы.',
    author: 'Татьяна Михайлова',
    authorId: 11,
    status: 'completed',
    priority: 'medium',
    progress: 100,
    deadline: '2026-03-15',
    createdAt: '2026-01-05',
    tags: ['API', 'CRM'],
    budget: '$12,500',
    teamSize: 2,
  },
  {
    id: 12,
    name: 'REST API для разработчиков',
    description: 'Публичный API с OAuth2, документацией Swagger и примерами на Python, JS и PHP. Поддержка вебхуков.',
    author: 'Артём Белов',
    authorId: 12,
    status: 'active',
    priority: 'high',
    progress: 83,
    deadline: '2026-05-10',
    createdAt: '2026-01-20',
    tags: ['API', 'Backend'],
    budget: '$22,000',
    teamSize: 4,
  },
  {
    id: 13,
    name: 'Персональные KPI-дашборды',
    description: 'Настраиваемые панели для каждого менеджера: цели, выполнение плана, рейтинг в команде.',
    author: 'Юлия Яковлева',
    authorId: 13,
    status: 'active',
    priority: 'medium',
    progress: 55,
    deadline: '2026-06-10',
    createdAt: '2026-02-28',
    tags: ['Analytics', 'Frontend'],
    budget: '$17,000',
    teamSize: 3,
  },
  {
    id: 14,
    name: 'Telegram-уведомления',
    description: 'Бот для мгновенных уведомлений о новых сделках, задачах и изменениях статусов прямо в Telegram.',
    author: 'Владимир Соколов',
    authorId: 14,
    status: 'completed',
    priority: 'low',
    progress: 100,
    deadline: '2026-02-15',
    createdAt: '2025-12-10',
    tags: ['API', 'Marketing'],
    budget: '$6,500',
    teamSize: 1,
  },
  {
    id: 15,
    name: 'Анализ тональности переписки',
    description: 'ML-модель определяет настроение клиента по переписке и сигнализирует менеджеру о рисках потери.',
    author: 'Надежда Павлова',
    authorId: 15,
    status: 'cancelled',
    priority: 'medium',
    progress: 22,
    deadline: '2026-05-01',
    createdAt: '2026-01-15',
    tags: ['AI', 'Analytics'],
    budget: '$41,000',
    teamSize: 5,
  },
  {
    id: 16,
    name: 'Мобильное приложение Android',
    description: 'Android-версия CRM-приложения с полным паритетом функций с iOS-версией.',
    author: 'Михаил Лебедев',
    authorId: 16,
    status: 'active',
    priority: 'high',
    progress: 27,
    deadline: '2026-09-30',
    createdAt: '2026-03-15',
    tags: ['Mobile', 'Android'],
    budget: '$48,000',
    teamSize: 5,
  },
  {
    id: 17,
    name: 'Система отчётности для бухгалтерии',
    description: 'Автоматическая генерация финансовых отчётов, экспорт в Excel и PDF, интеграция с банковским API.',
    author: 'Светлана Козлова',
    authorId: 17,
    status: 'paused',
    priority: 'medium',
    progress: 67,
    deadline: '2026-07-31',
    createdAt: '2026-02-01',
    tags: ['Backend', 'Analytics'],
    budget: '$19,500',
    teamSize: 3,
  },
  {
    id: 18,
    name: 'SSO и управление доступом',
    description: 'Single Sign-On через SAML и OIDC. Ролевая модель доступа с гранулярными правами на уровне объектов.',
    author: 'Андрей Орлов',
    authorId: 18,
    status: 'cancelled',
    priority: 'high',
    progress: 15,
    deadline: '2026-04-15',
    createdAt: '2026-02-10',
    tags: ['Security', 'Infrastructure'],
    budget: '$35,000',
    teamSize: 4,
  },
  {
    id: 19,
    name: 'Миграция на новый облачный кластер',
    description: 'Аварийный перенос всей инфраструктуры на новый Kubernetes-кластер после инцидента с провайдером. Требует нулевого даунтайма для клиентов.',
    author: 'Иван Иванов',
    authorId: 1,
    assignees: [
      { id: 1, name: 'Иван Иванов' },
      { id: 8, name: 'Дмитрий Попов' },
      { id: 18, name: 'Андрей Орлов' },
    ],
    status: 'active',
    priority: 'critical',
    progress: 34,
    deadline: '2026-05-03',
    createdAt: '2026-04-20',
    tags: ['DevOps', 'Infrastructure', 'Security'],
    budget: '$76,000',
    teamSize: 8,
  },
  {
    id: 20,
    name: 'Устранение утечки данных клиентов',
    description: 'Критическая уязвимость в API экспорта позволяла получать персональные данные без авторизации. Патч, аудит логов и уведомление регулятора.',
    author: 'Дмитрий Попов',
    authorId: 8,
    assignees: [
      { id: 8, name: 'Дмитрий Попов' },
      { id: 12, name: 'Артём Белов' },
    ],
    status: 'active',
    priority: 'critical',
    progress: 61,
    deadline: '2026-04-30',
    createdAt: '2026-04-25',
    tags: ['Security', 'Backend', 'API'],
    budget: '$28,000',
    teamSize: 4,
  },
]
