import { UserType } from '@/types/UserTypes'

export const usersData: UserType[] = [
  {
    id: 1,
    name: 'Иван Иванов',
    email: 'ivan.ivanov@company.com',
    createdAt: '2024-01-15',
  },
  {
    id: 2,
    name: 'Петр Петров',
    email: 'petr.petrov@company.com',
    createdAt: '2024-01-16',
  },
  {
    id: 3,
    name: 'Мария Сидорова',
    email: 'maria.sidorova@company.com',
    createdAt: '2024-01-17',
  },
  {
    id: 4,
    name: 'Алексей Козлов',
    email: 'alexey.kozlov@company.com',
    createdAt: '2024-01-18',
  },
  {
    id: 5,
    name: 'Елена Новикова',
    email: 'elena.novikova@company.com',
    createdAt: '2024-01-19',
  },
  {
    id: 6,
    name: 'Сергей Волков',
    email: 'sergey.volkov@company.com',
    createdAt: '2024-01-20',
  },
  {
    id: 7,
    name: 'Анна Кузнецова',
    email: 'anna.kuznetsova@company.com',
    createdAt: '2024-01-21',
  },
  {
    id: 8,
    name: 'Дмитрий Попов',
    email: 'dmitry.popov@company.com',
    createdAt: '2024-01-22',
  },
  {
    id: 9,
    name: 'Ольга Семенова',
    email: 'olga.semenova@company.com',
    createdAt: '2024-01-23',
  },
  {
    id: 10,
    name: 'Николай Федоров',
    email: 'nikolay.fedorov@company.com',
    createdAt: '2024-01-24',
  },
  {
    id: 11,
    name: 'Татьяна Михайлова',
    email: 'tatiana.mikhailova@company.com',
    createdAt: '2024-01-25',
  },
  {
    id: 12,
    name: 'Артем Белов',
    email: 'artem.belov@company.com',
    createdAt: '2024-01-26',
  },
  {
    id: 13,
    name: 'Юлия Яковлева',
    email: 'yulia.yakovleva@company.com',
    createdAt: '2024-01-27',
  },
  {
    id: 14,
    name: 'Владимир Соколов',
    email: 'vladimir.sokolov@company.com',
    createdAt: '2024-01-28',
  },
  {
    id: 15,
    name: 'Надежда Павлова',
    email: 'nadezhda.pavlova@company.com',
    createdAt: '2024-01-29',
  },
  {
    id: 16,
    name: 'Михаил Лебедев',
    email: 'mikhail.lebedev@company.com',
    createdAt: '2024-01-30',
  },
  {
    id: 17,
    name: 'Светлана Козлова',
    email: 'svetlana.kozlova@company.com',
    createdAt: '2024-01-31',
  },
  {
    id: 18,
    name: 'Андрей Орлов',
    email: 'andrey.orlov@company.com',
    createdAt: '2024-02-01',
  },
  {
    id: 19,
    name: 'Екатерина Зайцева',
    email: 'ekaterina.zaytseva@company.com',
    createdAt: '2024-02-02',
  },
  {
    id: 20,
    name: 'Павел Морозов',
    email: 'pavel.morozov@company.com',
    createdAt: '2024-02-03',
  },
  {
    id: 21,
    name: 'Ирина Васнецова',
    email: 'irina.vasnetsova@company.com',
    createdAt: '2024-02-04',
  },
  {
    id: 22,
    name: 'Константин Никитин',
    email: 'konstantin.nikitin@company.com',
    createdAt: '2024-02-05',
  },
  {
    id: 23,
    name: 'Лариса Фомина',
    email: 'larisa.fomina@company.com',
    createdAt: '2024-02-06',
  },
  {
    id: 24,
    name: 'Роман Жуков',
    email: 'roman.zhukov@company.com',
    createdAt: '2024-02-07',
  },
  {
    id: 25,
    name: 'Виктория Макарова',
    email: 'victoria.makarova@company.com',
    createdAt: '2024-02-08',
  },
  {
    id: 26,
    name: 'Григорий Егоров',
    email: 'grigory.egorov@company.com',
    createdAt: '2024-02-09',
  },
  {
    id: 27,
    name: 'Маргарита Степанова',
    email: 'margarita.stepanova@company.com',
    createdAt: '2024-02-10',
  },
  {
    id: 28,
    name: 'Вадим Борисов',
    email: 'vadim.borisov@company.com',
    createdAt: '2024-02-11',
  },
  {
    id: 29,
    name: 'Алина Данилова',
    email: 'alina.danilova@company.com',
    createdAt: '2024-02-12',
  },
  {
    id: 30,
    name: 'Станислав Тимофеев',
    email: 'stanislav.timofeev@company.com',
    createdAt: '2024-02-13',
  },
  {
    id: 31,
    name: 'Валерия Романова',
    email: 'valeria.romanova@company.com',
    createdAt: '2024-02-14',
  },
  {
    id: 32,
    name: 'Георгий Комаров',
    email: 'georgy.komarov@company.com',
    createdAt: '2024-02-15',
  },
  {
    id: 33,
    name: 'Диана Власова',
    email: 'diana.vlasova@company.com',
    createdAt: '2024-02-16',
  },
  {
    id: 34,
    name: 'Евгений Медведев',
    email: 'evgeny.medvedev@company.com',
    createdAt: '2024-02-17',
  },
  {
    id: 35,
    name: 'Зоя Алексеева',
    email: 'zoya.alexeeva@company.com',
    createdAt: '2024-02-18',
  },
  {
    id: 36,
    name: 'Игорь Тарасов',
    email: 'igor.tarasov@company.com',
    createdAt: '2024-02-19',
  },
  {
    id: 37,
    name: 'Ксения Соловьева',
    email: 'ksenia.solovieva@company.com',
    createdAt: '2024-02-20',
  },
  {
    id: 38,
    name: 'Леонид Васильев',
    email: 'leonid.vasilyev@company.com',
    createdAt: '2024-02-21',
  },
  {
    id: 39,
    name: 'Наталья Полякова',
    email: 'natalia.polyakova@company.com',
    createdAt: '2024-02-22',
  },
  {
    id: 40,
    name: 'Олег Григорьев',
    email: 'oleg.grigoryev@company.com',
    createdAt: '2024-02-23',
  },
  {
    id: 41,
    name: 'Раиса Федотова',
    email: 'raisa.fedotova@company.com',
    createdAt: '2024-02-24',
  },
  {
    id: 42,
    name: 'Семен Крылов',
    email: 'semen.krylov@company.com',
    createdAt: '2024-02-25',
  },
  {
    id: 43,
    name: 'Ульяна Максимова',
    email: 'ulyana.maximova@company.com',
    createdAt: '2024-02-26',
  },
  {
    id: 44,
    name: 'Федор Осипов',
    email: 'fedor.osipov@company.com',
    createdAt: '2024-02-27',
  },
  {
    id: 45,
    name: 'Харитон Савельев',
    email: 'khariton.savelyev@company.com',
    createdAt: '2024-02-28',
  },
  {
    id: 46,
    name: 'Цветана Родионова',
    email: 'tsvetana.rodionova@company.com',
    createdAt: '2024-02-29',
  },
  {
    id: 47,
    name: 'Эдуард Карпов',
    email: 'eduard.karpov@company.com',
    createdAt: '2024-03-01',
  },
  {
    id: 48,
    name: 'Юрий Афанасьев',
    email: 'yuri.afanasyev@company.com',
    createdAt: '2024-03-02',
  },
  {
    id: 49,
    name: 'Яна Щербакова',
    email: 'yana.shcherbakova@company.com',
    createdAt: '2024-03-03',
  },
  {
    id: 50,
    name: 'Адам Воронов',
    email: 'adam.voronov@company.com',
    createdAt: '2024-03-04',
  },
  {
    id: 51,
    name: 'Богдан Шестаков',
    email: 'bogdan.shestakov@company.com',
    createdAt: '2024-03-05',
  },
  {
    id: 52,
    name: 'Вера Демидова',
    email: 'vera.demidova@company.com',
    createdAt: '2024-03-06',
  },
  {
    id: 53,
    name: 'Галина Ершова',
    email: 'galina.ershova@company.com',
    createdAt: '2024-03-07',
  },
  {
    id: 54,
    name: 'Данил Тихонов',
    email: 'danil.tikhonov@company.com',
    createdAt: '2024-03-08',
  },
  {
    id: 55,
    name: 'Евдокия Сазонова',
    email: 'evdokia.sazonova@company.com',
    createdAt: '2024-03-09',
  },
  {
    id: 56,
    name: 'Жанна Казакова',
    email: 'zhanna.kazakova@company.com',
    createdAt: '2024-03-10',
  },
  {
    id: 57,
    name: 'Захар Ефимов',
    email: 'zakhar.efimov@company.com',
    createdAt: '2024-03-11',
  },
  {
    id: 58,
    name: 'Инна Калинина',
    email: 'inna.kalinina@company.com',
    createdAt: '2024-03-12',
  },
  {
    id: 59,
    name: 'Кирилл Логинов',
    email: 'kirill.loginov@company.com',
    createdAt: '2024-03-13',
  },
  {
    id: 60,
    name: 'Людмила Филатова',
    email: 'lyudmila.filatova@company.com',
    createdAt: '2024-03-14',
  },
]
